// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Order struct {
	ID        int64  `json:"id"`
	Owner     string `json:"owner"`
	ProductID int64  `json:"product_id"`
	// must be positive
	Quantity int64 `json:"quantity"`
	// must be positive
	Price     int64     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	// must be positive
	Cost int64 `json:"cost"`
	// must be positive
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	Username         string    `json:"username"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         string    `json:"full_name"`
	Email            string    `json:"email"`
	PasswordChangeAt time.Time `json:"password_change_at"`
	CreatedAt        time.Time `json:"created_at"`
}
